server:
  port: ${PORT:8080}

logging:
  level:
    root: WARN
    com.calcpro.flowmaster: INFO
    org.springframework.security: WARN

spring:
  application:
    name: flow-master
  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
